### PR TITLE
Add bower support

### PR DESCRIPTION
**Pull request by emertechie**
PR for [issue 1](https://github.com/peterkhayes/multisort/issues/1)

Note: readme will need to be tweaked. Remove mention of fork but keep `bower install multisort` instructions

### CODE REVIEW

**Comment by peterkhayes** [comment]
Looks mostly good.  My main issue is the addition of `lodash.map` - given that this library is pretty minimal in functionality, I would prefer to keep it dependency-free.  Could you re-implement map yourself and use that instead?  Could be as simple as `Object.keys(obj).map(function(key) {...})` if you want to map over an object.

Also, if you could update the readme to remove the "fork" piece, that would be great :)

**Comment by emertechie** [comment]
Updated after comments

**Comment by peterkhayes** [comment]
Looks good to me!

**Comment by peterkhayes** [comment]
I've published on NPM as 0.5.3

**Pull request merged**
